// Package tests provides end-to-end tests for {{.ProjectName}}.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package tests

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// E2E test helpers

// TestServer represents a test server for E2E tests
type TestServer struct {
	Echo *echo.Echo
}

// NewTestServer creates a new test server
func NewTestServer() *TestServer {
	e := echo.New()
	return &TestServer{Echo: e}
}

// Request makes a test request
func (s *TestServer) Request(method, path string, body interface{}) *httptest.ResponseRecorder {
	var reqBody *bytes.Buffer
	if body != nil {
		jsonBody, _ := json.Marshal(body)
		reqBody = bytes.NewBuffer(jsonBody)
	} else {
		reqBody = bytes.NewBuffer(nil)
	}

	req := httptest.NewRequest(method, path, reqBody)
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()

	s.Echo.ServeHTTP(rec, req)
	return rec
}

func TestE2EHealthCheck(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping E2E test in short mode")
	}

	server := NewTestServer()

	// Setup health endpoint
	server.Echo.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]interface{}{
			"status":  "healthy",
			"service": "{{.ServiceName}}",
			"version": "{{.ServiceVersion}}",
		})
	})

	t.Run("health check should return 200", func(t *testing.T) {
		rec := server.Request(http.MethodGet, "/health", nil)

		require.Equal(t, http.StatusOK, rec.Code)

		var response map[string]interface{}
		err := json.Unmarshal(rec.Body.Bytes(), &response)
		require.NoError(t, err)

		assert.Equal(t, "healthy", response["status"])
		assert.Equal(t, "{{.ServiceName}}", response["service"])
	})
}

func TestE2EAPIEndpoints(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping E2E test in short mode")
	}

	server := NewTestServer()

	// Setup API v1 group
	api := server.Echo.Group("/api/v1")

	api.GET("/ping", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{"message": "pong"})
	})

	t.Run("ping endpoint should return pong", func(t *testing.T) {
		rec := server.Request(http.MethodGet, "/api/v1/ping", nil)

		require.Equal(t, http.StatusOK, rec.Code)

		var response map[string]string
		err := json.Unmarshal(rec.Body.Bytes(), &response)
		require.NoError(t, err)

		assert.Equal(t, "pong", response["message"])
	})
}

func TestE2EErrorHandling(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping E2E test in short mode")
	}

	server := NewTestServer()

	server.Echo.GET("/error", func(c echo.Context) error {
		return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
	})

	server.Echo.GET("/not-found", func(c echo.Context) error {
		return echo.NewHTTPError(http.StatusNotFound, "Resource not found")
	})

	t.Run("should handle 500 errors", func(t *testing.T) {
		rec := server.Request(http.MethodGet, "/error", nil)
		assert.Equal(t, http.StatusInternalServerError, rec.Code)
	})

	t.Run("should handle 404 errors", func(t *testing.T) {
		rec := server.Request(http.MethodGet, "/not-found", nil)
		assert.Equal(t, http.StatusNotFound, rec.Code)
	})
}

func TestE2EValidation(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping E2E test in short mode")
	}

	server := NewTestServer()

	type CreateRequest struct {
		Name  string `json:"name" validate:"required"`
		Email string `json:"email" validate:"required,email"`
	}

	server.Echo.POST("/validate", func(c echo.Context) error {
		var req CreateRequest
		if err := c.Bind(&req); err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid request body")
		}

		if req.Name == "" || req.Email == "" {
			return echo.NewHTTPError(http.StatusBadRequest, "Missing required fields")
		}

		return c.JSON(http.StatusCreated, map[string]string{
			"message": "Created successfully",
		})
	})

	t.Run("should validate required fields", func(t *testing.T) {
		rec := server.Request(http.MethodPost, "/validate", map[string]string{})
		assert.Equal(t, http.StatusBadRequest, rec.Code)
	})

	t.Run("should accept valid request", func(t *testing.T) {
		rec := server.Request(http.MethodPost, "/validate", map[string]string{
			"name":  "Test User",
			"email": "test@example.com",
		})
		assert.Equal(t, http.StatusCreated, rec.Code)
	})
}
