// Package fixtures provides test fixtures and utilities for {{.ProjectName}}.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package fixtures

import (
	"os"

	"github.com/google/uuid"
)

// SetEnvVars sets environment variables for testing and returns a cleanup function
func SetEnvVars(vars map[string]string) func() {
	originalVars := make(map[string]string)

	// Store original values
	for key, value := range vars {
		originalVars[key] = os.Getenv(key)
		os.Setenv(key, value)
	}

	// Return cleanup function
	return func() {
		for key, originalValue := range originalVars {
			if originalValue == "" {
				os.Unsetenv(key)
			} else {
				os.Setenv(key, originalValue)
			}
		}
	}
}

// SampleEntity represents a sample entity for testing
type SampleEntity struct {
	ID   uuid.UUID
	Name string
}

// GetSampleEntity returns a sample entity for testing
func GetSampleEntity() *SampleEntity {
	return &SampleEntity{
		ID:   uuid.New(),
		Name: "Test Entity",
	}
}

// GetSampleEntities returns a slice of sample entities for testing
func GetSampleEntities(count int) []interface{} {
	entities := make([]interface{}, count)
	for i := 0; i < count; i++ {
		entities[i] = &SampleEntity{
			ID:   uuid.New(),
			Name: "Test Entity",
		}
	}
	return entities
}
