// Package mocks provides mock implementations for testing.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package mocks

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

// MockRepository is a generic mock repository implementation
type MockRepository struct {
	mock.Mock
	mu   sync.RWMutex
	data map[uuid.UUID]interface{}
}

// NewMockRepository creates a new mock repository
func NewMockRepository() *MockRepository {
	return &MockRepository{
		data: make(map[uuid.UUID]interface{}),
	}
}

// Create mocks creating an entity
func (m *MockRepository) Create(ctx context.Context, entity interface{}) error {
	args := m.Called(ctx, entity)
	return args.Error(0)
}

// FindByID mocks finding an entity by ID
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (interface{}, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0), args.Error(1)
}

// FindAll mocks finding all entities
func (m *MockRepository) FindAll(ctx context.Context, offset, limit int) ([]interface{}, int64, error) {
	args := m.Called(ctx, offset, limit)
	return args.Get(0).([]interface{}), args.Get(1).(int64), args.Error(2)
}

// Update mocks updating an entity
func (m *MockRepository) Update(ctx context.Context, entity interface{}) error {
	args := m.Called(ctx, entity)
	return args.Error(0)
}

// Delete mocks deleting an entity
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// MockLogger is a mock logger implementation
type MockLogger struct {
	mock.Mock
	mu       sync.RWMutex
	messages []string
}

// NewMockLogger creates a new mock logger
func NewMockLogger() *MockLogger {
	return &MockLogger{
		messages: make([]string, 0),
	}
}

// Info mocks info logging
func (m *MockLogger) Info(msg string, fields ...interface{}) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.messages = append(m.messages, msg)
	m.Called(msg, fields)
}

// Error mocks error logging
func (m *MockLogger) Error(msg string, fields ...interface{}) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.messages = append(m.messages, msg)
	m.Called(msg, fields)
}

// Debug mocks debug logging
func (m *MockLogger) Debug(msg string, fields ...interface{}) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.messages = append(m.messages, msg)
	m.Called(msg, fields)
}

// Warn mocks warn logging
func (m *MockLogger) Warn(msg string, fields ...interface{}) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.messages = append(m.messages, msg)
	m.Called(msg, fields)
}

// GetMessages returns all logged messages
func (m *MockLogger) GetMessages() []string {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.messages
}

// Reset clears all logged messages
func (m *MockLogger) Reset() {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.messages = make([]string, 0)
}

// MockValidator is a mock validator implementation
type MockValidator struct {
	mock.Mock
}

// NewMockValidator creates a new mock validator
func NewMockValidator() *MockValidator {
	return &MockValidator{}
}

// Validate mocks validation
func (m *MockValidator) Validate(i interface{}) error {
	args := m.Called(i)
	return args.Error(0)
}

// MockHTTPClient is a mock HTTP client implementation
type MockHTTPClient struct {
	mock.Mock
}

// NewMockHTTPClient creates a new mock HTTP client
func NewMockHTTPClient() *MockHTTPClient {
	return &MockHTTPClient{}
}

// Do mocks HTTP request execution
func (m *MockHTTPClient) Do(req interface{}) (interface{}, error) {
	args := m.Called(req)
	return args.Get(0), args.Error(1)
}
