// Package tests provides unit tests for {{.ProjectName}}.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package tests

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"

	"{{.ModulePath}}/tests/fixtures"
	"{{.ModulePath}}/tests/mocks"
)

// =============================================================================
// Test Helpers
// =============================================================================

// createTestContext creates a context with timeout for tests
func createTestContext(t *testing.T) (context.Context, context.CancelFunc) {
	return context.WithTimeout(context.Background(), 5*time.Second)
}

// =============================================================================
// Domain Entity Tests
// =============================================================================

func TestNewEntity(t *testing.T) {
	t.Run("should create entity with valid data", func(t *testing.T) {
		// arrange
		entity := fixtures.GetSampleEntity()

		// assert
		require.NotNil(t, entity)
		assert.NotEqual(t, uuid.Nil, entity.ID)
		assert.Equal(t, "Test Entity", entity.Name)
	})
}

// =============================================================================
// Repository Tests with Mocks
// =============================================================================

func TestRepository_Create(t *testing.T) {
	t.Run("should create entity successfully", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		entity := fixtures.GetSampleEntity()

		mockRepo.On("Create", ctx, entity).Return(nil)

		// act
		err := mockRepo.Create(ctx, entity)

		// assert
		require.NoError(t, err)
		mockRepo.AssertExpectations(t)
	})

	t.Run("should handle create error", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		entity := fixtures.GetSampleEntity()
		expectedErr := assert.AnError

		mockRepo.On("Create", ctx, entity).Return(expectedErr)

		// act
		err := mockRepo.Create(ctx, entity)

		// assert
		require.Error(t, err)
		assert.Equal(t, expectedErr, err)
		mockRepo.AssertExpectations(t)
	})
}

func TestRepository_FindByID(t *testing.T) {
	t.Run("should find entity by ID", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		entity := fixtures.GetSampleEntity()

		mockRepo.On("FindByID", ctx, entity.ID).Return(entity, nil)

		// act
		result, err := mockRepo.FindByID(ctx, entity.ID)

		// assert
		require.NoError(t, err)
		assert.Equal(t, entity, result)
		mockRepo.AssertExpectations(t)
	})

	t.Run("should return error for non-existent entity", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		id := uuid.New()

		mockRepo.On("FindByID", ctx, id).Return(nil, assert.AnError)

		// act
		result, err := mockRepo.FindByID(ctx, id)

		// assert
		require.Error(t, err)
		assert.Nil(t, result)
		mockRepo.AssertExpectations(t)
	})
}

func TestRepository_FindAll(t *testing.T) {
	t.Run("should return paginated results", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		entities := fixtures.GetSampleEntities(5)
		offset := 0
		limit := 10
		total := int64(5)

		mockRepo.On("FindAll", ctx, offset, limit).Return(entities, total, nil)

		// act
		result, count, err := mockRepo.FindAll(ctx, offset, limit)

		// assert
		require.NoError(t, err)
		assert.Len(t, result, 5)
		assert.Equal(t, total, count)
		mockRepo.AssertExpectations(t)
	})
}

func TestRepository_Update(t *testing.T) {
	t.Run("should update entity successfully", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		entity := fixtures.GetSampleEntity()

		mockRepo.On("Update", ctx, entity).Return(nil)

		// act
		err := mockRepo.Update(ctx, entity)

		// assert
		require.NoError(t, err)
		mockRepo.AssertExpectations(t)
	})
}

func TestRepository_Delete(t *testing.T) {
	t.Run("should delete entity successfully", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		id := uuid.New()

		mockRepo.On("Delete", ctx, id).Return(nil)

		// act
		err := mockRepo.Delete(ctx, id)

		// assert
		require.NoError(t, err)
		mockRepo.AssertExpectations(t)
	})
}

// =============================================================================
// Service Layer Tests
// =============================================================================

func TestService_Create(t *testing.T) {
	t.Run("should create entity through service", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		mockLogger := mocks.NewMockLogger()

		// Setup expectations
		mockRepo.On("Create", ctx, mock.Anything).Return(nil)
		mockLogger.On("Info", mock.Anything, mock.Anything).Maybe()

		// act & assert
		// Note: Replace with actual service implementation
		mockRepo.AssertExpectations(t)
	})
}

// =============================================================================
// Benchmark Tests
// =============================================================================

func BenchmarkEntityCreation(b *testing.B) {
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = fixtures.GetSampleEntity()
	}
}

func BenchmarkUUIDGeneration(b *testing.B) {
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = uuid.New()
	}
}

// =============================================================================
// Concurrent Access Tests
// =============================================================================

func TestRepository_ConcurrentAccess(t *testing.T) {
	t.Run("should handle concurrent reads", func(t *testing.T) {
		// arrange
		ctx, cancel := createTestContext(t)
		defer cancel()

		mockRepo := mocks.NewMockRepository()
		entity := fixtures.GetSampleEntity()

		mockRepo.On("FindByID", ctx, mock.Anything).Return(entity, nil)

		// act - concurrent reads
		done := make(chan bool, 10)
		for i := 0; i < 10; i++ {
			go func() {
				_, _ = mockRepo.FindByID(ctx, uuid.New())
				done <- true
			}()
		}

		// wait for all goroutines
		for i := 0; i < 10; i++ {
			<-done
		}

		// assert
		assert.True(t, mockRepo.AssertNumberOfCalls(t, "FindByID", 10))
	})
}
