# GolangCI-Lint Configuration (v2)
# TelemetryFlow SDK - Community Enterprise Observability Platform (CEOP)

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused
  exclusions:
    paths:
      - vendor

  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1019"
