// Package handler provides command handlers for {{.EntityName}} entity.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package handler

import (
	"context"

	"{{.ModulePath}}/internal/application/command"
	"{{.ModulePath}}/internal/domain/repository"
)

// {{.EntityName}}CommandHandler handles commands for {{.EntityName}} entity
type {{.EntityName}}CommandHandler struct {
	repo repository.{{.EntityName}}Repository
}

// New{{.EntityName}}CommandHandler creates a new {{.EntityName}} command handler
func New{{.EntityName}}CommandHandler(repo repository.{{.EntityName}}Repository) *{{.EntityName}}CommandHandler {
	return &{{.EntityName}}CommandHandler{
		repo: repo,
	}
}

// Handle{{.EntityName}}Create handles create {{lower .EntityName}} command
func (h *{{.EntityName}}CommandHandler) Handle{{.EntityName}}Create(ctx context.Context, cmd *command.Create{{.EntityName}}Command) error {
	entity := cmd.ToEntity()
	return h.repo.Create(ctx, entity)
}

// Handle{{.EntityName}}Update handles update {{lower .EntityName}} command
func (h *{{.EntityName}}CommandHandler) Handle{{.EntityName}}Update(ctx context.Context, cmd *command.Update{{.EntityName}}Command) error {
	entity := cmd.ToEntity()
	return h.repo.Update(ctx, entity)
}

// Handle{{.EntityName}}Delete handles delete {{lower .EntityName}} command
func (h *{{.EntityName}}CommandHandler) Handle{{.EntityName}}Delete(ctx context.Context, cmd *command.Delete{{.EntityName}}Command) error {
	return h.repo.Delete(ctx, cmd.ID)
}