-- Migration: Create {{snake .EntityNamePlural}} table
-- Generated by TelemetryFlow RESTful API Generator
-- Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

CREATE TABLE IF NOT EXISTS {{snake .EntityNamePlural}} (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
{{range .EntityFields}}{{if ne .Name "ID"}}    {{.DBColumn}} {{if eq .GoType "string"}}VARCHAR(255){{else if eq .GoType "int"}}INTEGER{{else if eq .GoType "int64"}}BIGINT{{else if eq .GoType "float64"}}DECIMAL(10,2){{else if eq .GoType "bool"}}BOOLEAN{{else if eq .GoType "time.Time"}}TIMESTAMP{{else if eq .GoType "uuid.UUID"}}UUID{{else}}TEXT{{end}}{{if not .Nullable}} NOT NULL{{end}},
{{end}}{{end}}    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_{{snake .EntityNamePlural}}_created_at ON {{snake .EntityNamePlural}}(created_at);
{{range .EntityFields}}{{if eq .GoType "uuid.UUID"}}CREATE INDEX IF NOT EXISTS idx_{{snake $.EntityNamePlural}}_{{.DBColumn}} ON {{snake $.EntityNamePlural}}({{.DBColumn}});
{{end}}{{end}}

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_{{snake .EntityNamePlural}}_updated_at
    BEFORE UPDATE ON {{snake .EntityNamePlural}}
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();