-- Migration: Drop {{snake .EntityNamePlural}} table
-- Generated by TelemetryFlow RESTful API Generator
-- Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

-- Drop trigger
DROP TRIGGER IF EXISTS update_{{snake .EntityNamePlural}}_updated_at ON {{snake .EntityNamePlural}};

-- Drop indexes
DROP INDEX IF EXISTS idx_{{snake .EntityNamePlural}}_created_at;
{{range .EntityFields}}{{if eq .GoType "uuid.UUID"}}DROP INDEX IF EXISTS idx_{{snake $.EntityNamePlural}}_{{.DBColumn}};
{{end}}{{end}}

-- Drop table
DROP TABLE IF EXISTS {{snake .EntityNamePlural}};