// Package persistence provides repository implementations for {{.EntityName}} entity.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package persistence

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"{{.ModulePath}}/internal/domain/entity"
	"{{.ModulePath}}/internal/domain/repository"
	"gorm.io/gorm"
)

// {{lower .EntityName}}Repository implements repository.{{.EntityName}}Repository
type {{lower .EntityName}}Repository struct {
	db *gorm.DB
}

// New{{.EntityName}}Repository creates a new {{.EntityName}} repository
func New{{.EntityName}}Repository(db *gorm.DB) repository.{{.EntityName}}Repository {
	return &{{lower .EntityName}}Repository{
		db: db,
	}
}

// Create creates a new {{lower .EntityName}}
func (r *{{lower .EntityName}}Repository) Create(ctx context.Context, e *entity.{{.EntityName}}) error {
	return r.db.WithContext(ctx).Create(e).Error
}

// FindByID retrieves a {{lower .EntityName}} by ID
func (r *{{lower .EntityName}}Repository) FindByID(ctx context.Context, id uuid.UUID) (*entity.{{.EntityName}}, error) {
	var e entity.{{.EntityName}}
	err := r.db.WithContext(ctx).First(&e, "id = ?", id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errors.New("{{lower .EntityName}} not found")
		}
		return nil, err
	}
	return &e, nil
}

// FindAll retrieves all {{lower .EntityNamePlural}} with pagination
func (r *{{lower .EntityName}}Repository) FindAll(ctx context.Context, offset, limit int) ([]entity.{{.EntityName}}, int64, error) {
	var {{lower .EntityNamePlural}} []entity.{{.EntityName}}
	var total int64

	// Count total records
	if err := r.db.WithContext(ctx).Model(&entity.{{.EntityName}}{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}

	// Get paginated records
	if err := r.db.WithContext(ctx).
		Order("created_at DESC").
		Offset(offset).
		Limit(limit).
		Find(&{{lower .EntityNamePlural}}).Error; err != nil {
		return nil, 0, err
	}

	return {{lower .EntityNamePlural}}, total, nil
}

// Update updates a {{lower .EntityName}}
func (r *{{lower .EntityName}}Repository) Update(ctx context.Context, e *entity.{{.EntityName}}) error {
	return r.db.WithContext(ctx).Save(e).Error
}

// Delete soft-deletes a {{lower .EntityName}} by ID
func (r *{{lower .EntityName}}Repository) Delete(ctx context.Context, id uuid.UUID) error {
	return r.db.WithContext(ctx).Delete(&entity.{{.EntityName}}{}, "id = ?", id).Error
}

// HardDelete permanently deletes a {{lower .EntityName}} by ID
func (r *{{lower .EntityName}}Repository) HardDelete(ctx context.Context, id uuid.UUID) error {
	return r.db.WithContext(ctx).Unscoped().Delete(&entity.{{.EntityName}}{}, "id = ?", id).Error
}
{{- range .EntityFields}}
{{- if eq .Type "string"}}

// FindBy{{.Name}} finds {{$.EntityNamePlural}} by {{.Name}}
func (r *{{lower $.EntityName}}Repository) FindBy{{.Name}}(ctx context.Context, {{.JSONName}} string) ([]entity.{{$.EntityName}}, error) {
	var {{lower $.EntityNamePlural}} []entity.{{$.EntityName}}
	err := r.db.WithContext(ctx).
		Where("{{.DBColumn}} = ?", {{.JSONName}}).
		Order("created_at DESC").
		Find(&{{lower $.EntityNamePlural}}).Error
	if err != nil {
		return nil, err
	}
	return {{lower $.EntityNamePlural}}, nil
}
{{- end}}
{{- end}}
