// Package handler provides query handlers for {{.EntityName}} entity.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package handler

import (
	"context"

	"{{.ModulePath}}/internal/application/dto"
	"{{.ModulePath}}/internal/application/query"
	"{{.ModulePath}}/internal/domain/repository"
)

// {{.EntityName}}QueryHandler handles queries for {{.EntityName}} entity
type {{.EntityName}}QueryHandler struct {
	repo repository.{{.EntityName}}Repository
}

// New{{.EntityName}}QueryHandler creates a new {{.EntityName}} query handler
func New{{.EntityName}}QueryHandler(repo repository.{{.EntityName}}Repository) *{{.EntityName}}QueryHandler {
	return &{{.EntityName}}QueryHandler{
		repo: repo,
	}
}

// Handle{{.EntityName}}GetByID handles get {{lower .EntityName}} by ID query
func (h *{{.EntityName}}QueryHandler) Handle{{.EntityName}}GetByID(ctx context.Context, qry *query.Get{{.EntityName}}ByIDQuery) (*dto.{{.EntityName}}Response, error) {
	entity, err := h.repo.FindByID(ctx, qry.ID)
	if err != nil {
		return nil, err
	}
	return dto.{{.EntityName}}ToResponse(entity), nil
}

// Handle{{.EntityName}}GetAll handles get all {{lower .EntityNamePlural}} query
func (h *{{.EntityName}}QueryHandler) Handle{{.EntityName}}GetAll(ctx context.Context, qry *query.GetAll{{.EntityNamePlural}}Query) (*dto.{{.EntityName}}ListResponse, error) {
	entities, total, err := h.repo.FindAll(ctx, qry.Offset, qry.Limit)
	if err != nil {
		return nil, err
	}

	responses := make([]*dto.{{.EntityName}}Response, len(entities))
	for i := range entities {
		responses[i] = dto.{{.EntityName}}ToResponse(&entities[i])
	}

	return &dto.{{.EntityName}}ListResponse{
		Data:   responses,
		Total:  total,
		Offset: qry.Offset,
		Limit:  qry.Limit,
	}, nil
}
