#!/bin/bash
# {{.ProjectName}} - Run Script
# Generated by TelemetryFlow RESTful API Generator

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Starting {{.ProjectName}}...${NC}"

# Check if .env exists
if [ ! -f .env ]; then
    echo -e "${YELLOW}Warning: .env file not found. Copying from .env.example${NC}"
    if [ -f .env.example ]; then
        cp .env.example .env
        echo -e "${YELLOW}Please update .env with your configuration${NC}"
    else
        echo -e "${RED}Error: .env.example not found${NC}"
        exit 1
    fi
fi

# Load environment variables
export $(grep -v '^#' .env | xargs)

# Check for required binaries
if ! command -v go &> /dev/null; then
    echo -e "${RED}Error: Go is not installed${NC}"
    exit 1
fi

# Build if needed
if [ ! -f ./build/{{.ProjectName | lower}} ] || [ "$1" == "--rebuild" ]; then
    echo -e "${GREEN}Building...${NC}"
    make build
fi

# Run the application
echo -e "${GREEN}Running on port ${SERVER_PORT:-{{.ServerPort}}}${NC}"
./build/{{.ProjectName | lower}}
