#!/bin/bash
# {{.ProjectName}} - Test Script
# Generated by TelemetryFlow RESTful API Generator

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

# Test mode
MODE=${1:-all}

echo -e "${GREEN}Running tests (mode: $MODE)...${NC}"

case $MODE in
    unit)
        echo -e "${GREEN}Running unit tests...${NC}"
        go test -v -race -short ./tests/unit/...
        ;;
    integration)
        echo -e "${GREEN}Running integration tests...${NC}"
        go test -v -race ./tests/integration/...
        ;;
    e2e)
        echo -e "${GREEN}Running E2E tests...${NC}"
        go test -v ./tests/e2e/...
        ;;
    coverage)
        echo -e "${GREEN}Running tests with coverage...${NC}"
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html
        echo -e "${GREEN}Coverage report: coverage.html${NC}"
        ;;
    short)
        echo -e "${GREEN}Running short tests (skip E2E)...${NC}"
        go test -v -race -short ./...
        ;;
    all|*)
        echo -e "${GREEN}Running all tests...${NC}"
        go test -v -race ./...
        ;;
esac

echo -e "${GREEN}Tests completed!${NC}"
