-- {{.ProjectName}} - Initial Migration
-- Generated by TelemetryFlow RESTful API Generator

-- Enable UUID extension (PostgreSQL)
{{- if eq .DBDriver "postgres"}}
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
{{- end}}

{{- if .EnableAuth}}

-- Users table
CREATE TABLE IF NOT EXISTS users (
{{- if eq .DBDriver "postgres"}}
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
{{- else if eq .DBDriver "mysql"}}
    id CHAR(36) PRIMARY KEY,
{{- else}}
    id TEXT PRIMARY KEY,
{{- end}}
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT true,
{{- if eq .DBDriver "postgres"}}
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
{{- else}}
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
{{- end}}
);

-- Indexes for users
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_deleted_at ON users(deleted_at);

-- Refresh tokens table
CREATE TABLE IF NOT EXISTS refresh_tokens (
{{- if eq .DBDriver "postgres"}}
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
{{- else if eq .DBDriver "mysql"}}
    id CHAR(36) PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
{{- else}}
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
{{- end}}
    token VARCHAR(500) NOT NULL UNIQUE,
{{- if eq .DBDriver "postgres"}}
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
{{- else}}
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
{{- end}}
);

-- Indexes for refresh_tokens
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

{{- end}}
