{
  "info": {
    "name": "{{.ProjectName}} API",
    "description": "{{.ServiceName}} - RESTful API with DDD + CQRS Pattern\n\nGenerated by TelemetryFlow RESTful API Generator",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "variable": [
    {
      "key": "baseUrl",
      "value": "http://localhost:{{.ServerPort}}",
      "type": "string"
    },
    {
      "key": "apiVersion",
      "value": "v1",
      "type": "string"
    }
{{- if .EnableAuth}},
    {
      "key": "accessToken",
      "value": "",
      "type": "string"
    }
{{- end}}
  ],
  "item": [
    {
      "name": "Health",
      "description": "Health check endpoints",
      "item": [
        {
          "name": "Health Check",
          "request": {
            "method": "GET",
            "header": [],
            "url": {
              "raw": "{{`{{baseUrl}}`}}/health",
              "host": ["{{`{{baseUrl}}`}}"],
              "path": ["health"]
            },
            "description": "Check if the service is healthy"
          },
          "response": [],
          "event": [
            {
              "listen": "test",
              "script": {
                "exec": [
                  "// BDD Test: Health Check",
                  "pm.test('Given the API is running', function() {",
                  "    pm.test('When I request the health endpoint', function() {",
                  "        pm.test('Then the response status should be 200', function() {",
                  "            pm.response.to.have.status(200);",
                  "        });",
                  "        pm.test('And the status should be healthy', function() {",
                  "            const response = pm.response.json();",
                  "            pm.expect(response.status).to.eql('healthy');",
                  "        });",
                  "    });",
                  "});"
                ],
                "type": "text/javascript"
              }
            }
          ]
        },
        {
          "name": "Readiness Check",
          "request": {
            "method": "GET",
            "header": [],
            "url": {
              "raw": "{{`{{baseUrl}}`}}/ready",
              "host": ["{{`{{baseUrl}}`}}"],
              "path": ["ready"]
            },
            "description": "Check if the service is ready to accept requests"
          },
          "response": [],
          "event": [
            {
              "listen": "test",
              "script": {
                "exec": [
                  "// BDD Test: Readiness Check",
                  "pm.test('Given the API is running', function() {",
                  "    pm.test('When I request the ready endpoint', function() {",
                  "        pm.test('Then the response status should be 200', function() {",
                  "            pm.response.to.have.status(200);",
                  "        });",
                  "        pm.test('And all dependencies should be healthy', function() {",
                  "            const response = pm.response.json();",
                  "            pm.expect(response.status).to.be.oneOf(['ready', 'healthy']);",
                  "        });",
                  "    });",
                  "});"
                ],
                "type": "text/javascript"
              }
            }
          ]
        }
      ]
    }
{{- if .EnableAuth}},
    {
      "name": "Auth",
      "description": "Authentication endpoints",
      "item": [
        {
          "name": "Login",
          "request": {
            "method": "POST",
            "header": [
              {
                "key": "Content-Type",
                "value": "application/json"
              }
            ],
            "body": {
              "mode": "raw",
              "raw": "{\n    \"email\": \"user@example.com\",\n    \"password\": \"password123\"\n}"
            },
            "url": {
              "raw": "{{`{{baseUrl}}`}}/api/{{`{{apiVersion}}`}}/auth/login",
              "host": ["{{`{{baseUrl}}`}}"],
              "path": ["api", "{{`{{apiVersion}}`}}", "auth", "login"]
            },
            "description": "Authenticate and get access token"
          },
          "response": [],
          "event": [
            {
              "listen": "test",
              "script": {
                "exec": [
                  "// BDD Test: Login",
                  "pm.test('Given valid credentials', function() {",
                  "    pm.test('When I submit login request', function() {",
                  "        pm.test('Then I should receive access token', function() {",
                  "            pm.response.to.have.status(200);",
                  "            const response = pm.response.json();",
                  "            pm.expect(response.data).to.have.property('access_token');",
                  "            // Store token for subsequent requests",
                  "            pm.collectionVariables.set('accessToken', response.data.access_token);",
                  "        });",
                  "    });",
                  "});"
                ],
                "type": "text/javascript"
              }
            }
          ]
        }
      ]
    }
{{- end}}
  ]
}
